services:
  - type: web
    name: 3wpoultryfarm
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: poultry-db
          property: connectionString
    autoDeploy: true

databases:
  - name: poultry-db
    plan: free